[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/systems-map/*"
  to = "/systems-map/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
